/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CityController;
import Controller.DistanceController;
import Model.City;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Poshitha_Ravindu
 */
public class AddNewDistance extends javax.swing.JFrame {

    ArrayList<City> cityList ;
    City firstCity ;
    City secCity;
    /**
     * Creates new form AddNewDistance
     */
    public AddNewDistance() {
        cityList = new ArrayList<>();
        firstCity = new City();
        secCity = new City();
        initComponents();
        loadCitiesToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secCityCmb = new javax.swing.JComboBox<>();
        fistCityCmb = new javax.swing.JComboBox<>();
        distanceTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add New Distance Between Cites");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("City to");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Distance");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("City from");

        secCityCmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        secCityCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City" }));
        secCityCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCityCmbActionPerformed(evt);
            }
        });

        fistCityCmb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fistCityCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City" }));
        fistCityCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fistCityCmbActionPerformed(evt);
            }
        });

        distanceTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        distanceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                distanceTxtKeyTyped(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setText("Add ");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(secCityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fistCityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fistCityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(secCityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(distanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        try{
        if(firstCity.getCityName().equals(secCity.getCityName()) || secCity.getCityName().equals(firstCity.getCityName()) ){
            JOptionPane.showMessageDialog(this, "Invalid City inputs try again", "Error.", JOptionPane.ERROR_MESSAGE);  
        }else if(distanceTxt.getText().toString().equals("")){
           JOptionPane.showMessageDialog(this, "Enter distance between two cites", "Error.", JOptionPane.ERROR_MESSAGE);  
        }else{
            
            if(DistanceController.getSelectedDistanceDetails(firstCity, secCity,Integer.parseInt(distanceTxt.getText().toString()))){
                
                DistanceController.addNewDistance(firstCity, secCity,Integer.parseInt(distanceTxt.getText().toString()));
                JOptionPane.showMessageDialog(this, "Distance saved successfully", "Success.", JOptionPane.INFORMATION_MESSAGE);
                distanceTxt.setText("");
                fistCityCmb.setSelectedIndex(0);
                secCityCmb.setSelectedIndex(0);
            }else{
                JOptionPane.showMessageDialog(this, "You have enterd the distance before", "Error.", JOptionPane.ERROR_MESSAGE);  
            }
        }
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Enter both cites", "Error.", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void fistCityCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fistCityCmbActionPerformed
        // TODO add your handling code here:
        firstCity = this.getSelectedCityinCmb(fistCityCmb);
    }//GEN-LAST:event_fistCityCmbActionPerformed

    private void secCityCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCityCmbActionPerformed
        // TODO add your handling code here:
         secCity = this.getSelectedCityinCmb(secCityCmb);
    }//GEN-LAST:event_secCityCmbActionPerformed

    /**
     * set only numeric values to txt box
     **/
    private void distanceTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceTxtKeyTyped
        // TODO add your handling code here:
        
        char vchar = evt.getKeyChar();
        if(!(Character.isDigit(vchar)) 
                || (vchar == KeyEvent.VK_BACKSPACE)
                || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_distanceTxtKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNewDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNewDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNewDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNewDistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNewDistance().setVisible(true);
//            }
//        });
//    }
    public void loadCitiesToComboBox(){
        
        cityList = CityController.getAllCities();
        
        for(City city:cityList){
            fistCityCmb.addItem(city.getCityName());
            secCityCmb.addItem(city.getCityName());
        }
    }
    
    public City getSelectedCityinCmb(JComboBox<String> cmb){
        City selectedCity = null ;
        String key = cmb.getSelectedItem().toString();
        for(City city:cityList){
            
            if(city.getCityName().equals(key)){
               selectedCity = new City();
               selectedCity.setCityID(city.getCityID());
               selectedCity.setCityName(city.getCityName());
            }
        }
        return selectedCity;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField distanceTxt;
    private javax.swing.JComboBox<String> fistCityCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> secCityCmb;
    // End of variables declaration//GEN-END:variables
}
