/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DijkstraMethodController;
import Controller.DistanceController;
import DB.DBConnection;
import Model.Distance;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poshitha_Ravindu
 */
public class DistanceDetailFrame extends javax.swing.JFrame {

    Distance selectedDistance ;
    /**
     * Creates new form DistanceDetailFrame
     */
    public DistanceDetailFrame() {
        initComponents();
        this.loadDistances();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        distanceTbl = new javax.swing.JTable();
        delBtn = new javax.swing.JToggleButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        addNewCityMenu = new javax.swing.JMenuItem();
        addDistanceMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        shortestParthDrop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        distanceTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City 1", "City 2", "Distance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        distanceTbl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                distanceTblFocusLost(evt);
            }
        });
        distanceTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distanceTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(distanceTbl);

        delBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delBtn.setText("Delete");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jMenu4.setText("File");

        addNewCityMenu.setText("Add New City");
        addNewCityMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCityMenuActionPerformed(evt);
            }
        });
        jMenu4.add(addNewCityMenu);

        addDistanceMenu.setText("Add Distance");
        addDistanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDistanceMenuActionPerformed(evt);
            }
        });
        jMenu4.add(addDistanceMenu);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");

        shortestParthDrop.setText("ShortestPath");
        shortestParthDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortestParthDropActionPerformed(evt);
            }
        });
        jMenu5.add(shortestParthDrop);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewCityMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCityMenuActionPerformed
       new AddNewCityView().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_addNewCityMenuActionPerformed

    private void addDistanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDistanceMenuActionPerformed
        // TODO add your handling code here:
        new AddNewDistance().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addDistanceMenuActionPerformed

    private void distanceTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distanceTblMouseClicked
        // TODO add your handling code here:
        
         int row=distanceTbl.rowAtPoint(evt.getPoint());

           String cityOne =  distanceTbl.getValueAt(row,0).toString();
           String cityTwo = distanceTbl.getValueAt(row,1).toString();
           float distance =  Float.parseFloat(distanceTbl.getValueAt(row,2).toString());
          
           if (selectedDistance == null){
            selectedDistance = new Distance(0, 0, distance);
         }else{
             selectedDistance.setDistance(distance);
           }
            selectedDistance.setFistCityName(cityOne);
            selectedDistance.setSecCityName(cityTwo);
            
           
           delBtn.setEnabled(true);
           
                                        
    }//GEN-LAST:event_distanceTblMouseClicked

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
        
       DistanceController.deleteSelectedDistance(selectedDistance);
       loadDistances();
        
    }//GEN-LAST:event_delBtnActionPerformed

    private void distanceTblFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_distanceTblFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_distanceTblFocusLost

    private void shortestParthDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortestParthDropActionPerformed
        // TODO add your handling code here:
        new  DijkstraView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_shortestParthDropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistanceDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistanceDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistanceDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistanceDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistanceDetailFrame().setVisible(true);
            }
        });
        
        
    }
    
    public void loadDistances(){
        ArrayList<Distance> distanceList = DistanceController.getAllDistances();
        DefaultTableModel dtm = (DefaultTableModel) distanceTbl.getModel();
        dtm.setRowCount(0);
        for(Distance dis:distanceList){
            dtm.addRow(new Object[]{dis.getFistCityName(),dis.getSecCityName(),dis.getDistance()});
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addDistanceMenu;
    private javax.swing.JMenuItem addNewCityMenu;
    private javax.swing.JToggleButton delBtn;
    private javax.swing.JTable distanceTbl;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem shortestParthDrop;
    // End of variables declaration//GEN-END:variables
}
